---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ecommerce-api-gateway-secret
  namespace: ecommerce-api-gateway
spec:
  encryptedData:
    TOKEN_SECRET: AgAXbMGJfo2Gh9VZM4AFIHIwUAgGx9bYNV6eXz5rnM9BcQZ2doZgoWoWWBn/hxvpfnDqOwY1pywFM7FQGpLnQVYW5hzt5wStLRlxiVW5u0POXUT5O66rqSdm6LnFFUeNJP6LUixK7AX9je5nUzBguzPEaMgqvZXZKieUJPccLFZr9gk2opg6BfMqQ21DXvjKK0DhOH85Tgw1CBJJYHT47Scm/VKhioZmrj5Ii3PrcwOxY2GqePTPEdj9YNMZKvwN6xks7aQZ168O4KtTpnvaVvkzPb/oWFFHebtLlnAo9+ArZAR2ePkEkivH+rzkTH/gONpQmBVtk5Ln/f1FSzuCwnmfoDDrdfqPdTeQOpBjZ9lEiaYVrN1J/rGlI4OEDJ9VmZOsAksSM79NpVx7HFfw8etQL+YgDJoG/wyQgPfMw4/H9GKgPLTruJAEt7GR0qHuSttsT6Am+Gqsa9TdUpZWhmUm9n8PcTuhklRkj7QSSIDqR0flEC7K1OYVRK/PRASuvE6BJcYyKT6UpPwO5MsGih1k5fgyOMgAQsIPAey0SBTPISlatRqT19qfe30PLBSsQYLwIBq3IuO+MmarNA2qsITAZOHIn1D9BUwbq83Z013CdqdnGvyr8i7jtxwctlsa7XpZNNsRN+lR6wMMH9S51K06Yl27dJWDLeRGJfZzAkI9/6GcjKsm6jcThTIHaAP5XYa72+LqrsQ4gq3OnMIA89fqSq7+
  template:
    metadata:
      name: ecommerce-api-gateway-secret
      namespace: ecommerce-api-gateway
