---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ecommerce-api-gateway-secret
  namespace: ecommerce-api-gateway
spec:
  encryptedData:
    TOKEN_SECRET: AgCdDA6u1HLZ2HTEUiARG14YDzM0rOgi3AvioTmZM4S44y+1+qRkRUU7U9STkHEvTgSd+7hcTBCO5CDbaR/09O9NkV8Ab45Jdjd0tWpuF9Z8Bm3+JRvUJQ1BY0ELDmDZF+gx/C7ZlzhLO2kRzsS/xGi7PedBq2zhC7kVdRFvfMMd10dAYvqbkq0T5PNpIj5qBsvsVdMtvfdD1T5OtnK+9n8YYuzkUuP0AavZb+MeufEgknxY64e8jrZzu825M8zeuaQp4aA/4Ae3t/J+JFHsWRCyTGm6z4D/zZwqv0vOJlpCfVc9yWFP5xoMqMdqnVoH2d0SxhMYwJubaCYmo5RFXELNRmNUai+q28C6RLK4AJbj0xK9ZFKFN6TCYFHpqXvZpHW11pocWhRwCKuCey+XgngSkHHtafSunvbx+DQcdQZHil4Fb/gE8aUFTWNiNgWGdxnHut/iO5fkwxvfJ2gA59B19REGjbBvfCG09yk767P+MJJI/ZCdLTEDCQnWIdW9PE6jc/+W4AyE+0IAtiCj/KgGCfYnVMCYSKah8o341AzD5AUfnUJsuNVRnOgp1X5yqwMdiGGh6zBqeXqFMX1y1KByTTj7s5iPTnzgTvWsQOCM5dIqajRxs2c3noPOsa/7tpYwn5JCKtLtBuXJk+Nytthc8b8oiP3OmQtgaK6n/TiqcwoZZDU55kfkpRwYBbD8GoS1Dea6oGILBLwd1LYlBjBS5kz2
  template:
    metadata:
      name: ecommerce-api-gateway-secret
      namespace: ecommerce-api-gateway
