---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ecommerce-api-gateway-secret
  namespace: ecommerce-api-gateway
spec:
  encryptedData:
    TOKEN_SECRET: AgANtBAqzpktL5HpmKfwz4YA0CCs2ZAHD+GAFJXZDH55VDyPgpy9WQ3CtQvVyb1dNRyU1aUzaqUDz1/z8BNmGJ2ltl1SAHF+Zk5IGPOEhzAwllqXM+/N/VjrSy05WTiFhJAR1gYK5mhHz5KLKZHennwRHl9lSx7LLOBnh8NIQYJdQ7amRCZb1mT4gPz6NUnC4O/D6bXP2i1q5n/CnSWiI9eHRXo2ydxRloTxbjBWMszwT/CqCtkCzzC2tr/NpKuOnF5ztGJQceRJ3Z6fNIyU+HugNUwb3bL1njb4SLz5BnJ5JP5c2iuNc7f3mW+R99oIPeK4r7W7d5IRP6NByjpdUF2IRu5LJJJsc9JCA96HM7OaCyQkMpzhgnSZOognGiViYlroJX8RVgY5DVGfK2ORDx5k4EeFiBL6w2gHDeel1MRj27b0IsLwyWhjqIUw/HXamqxIcNLOtbXCL3kvuBx3mNv30YXlWEbMmKkYY/P5lbNL4YjBqK3swYrgYjf2AHe3jBidwYmrob3qLiF4Bi0enbYtFRYWPz+yFsDiTINb6iyVJTbHuygS/gq5hnkHhYD06SL9JOeLEMx0verQz4JDGXmXVv6tmKST2K3VtRiyphMbjT539ocaMuWFbF9PcLMFRrXDKVfjy4ycPtJXf8L2KDbla2rwlPJdjefZw76LEigsFYYCdR8IshKD7QBDL72jzbAxdOjbakIHu5YGzb7rQzKyA9l2
  template:
    metadata:
      name: ecommerce-api-gateway-secret
      namespace: ecommerce-api-gateway
