---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ecommerce-keycloak-secret
  namespace: ecommerce-keycloak
spec:
  encryptedData:
    KEYCLOAK_ADMIN_PASSWORD: AgDYJRERg8h1rufe0ZLZD49KPthodOwLi+aGGx7hZV5zwvb4pzD6mV7E5ubSBtH3hncUGF/ZNJ1YyjTrYah1iwPyHM7deFouNQ9KVhzSU0W7MGJP7ERIBT0WoaP6dzk76K2sIBWE+/j6HaBM7BYUIKMv9eeR0/7tm08xTYfoHOsPHZWxpS2IhNcyXtI/uYTNM0ijd7Li/dDNujEhokv+qo1yTQb1JGyML1nRc4kh3jcP2ByX9ZbqIbAk2kMIHKGDGaEbapSAOh7rxWPUH7Y/srorMD9CxFXEzA8I3pdL8EImo7Lvob8mOIo8jIm2XE39gheGuqgil8tIArnVVFw+o9RPEkv+mudYwodkkmksZfOyYRtiKTrcv0m77DnCKC9nMeEsBAsCLXpS9oaOw4jjDE8cfKr0teRPMhlmHybO6ipAxuu7tBmIP00I8naZA3zc/860Rqq3ecDAsmDKyC3fD+uFGOYXpO5uxwdO8QuiG4YY8BaD40FJ+cVnxgnGTP1eyP6qzqfuOK0dgLtlHLXYD8o+sF54wE2/e8lSSjusLVVmdFRk6MVed+sMiLKv1mwbS+Ey/HJXU2MqZ9AMtENw6UPe/DowuzRAiLTXrBQXez9L5TmMGaURPCQ2TyqHv8kaZjvf++9Q4nw/ZTlvj3t8FXVFUM6bnWs4Cx20Sh/5RYl+f9UedgNECxJHD3HSUtCAUG3oHYZy9jtlEpsKP50=
    KEYCLOAK_DB_PASSWORD: AgA9rZfzSh3Elak2Omg8LMP10urZFuGkIweMxGVe7l9uYGalQqf2XwIjKGdm372PAHHLrXF5+zRC2qufUHgiXQegI4kS5VDqvKSYi7UZ4cGevLyYBO9ELDyvBLLPXW34E1sniQSS7a7O/iJQJH2z1JZ9GqeEXJhWwiAto1KEPBfiQse9A0HrRwgvZ0MjTLfe3qcI6Nsz+tsoYpaXj1nBw4Wj7ifdGik9/0mQ+HWIXkpCocBCJSB6NauYp5IpUx2c2bZQ+qqr4chgwBaeEP2dnRlMacSlxvXyXzAceC1mhQYdeEjN8HHaOBYXW8dPkjp3RCIfL+MzxfK2kHr+nc7xCby8DUpcTHS1JpzVa+/IY+UT/RLRq/aywkQeAfeED0ZMF9vzFy9kWaOUH5258PQYhk7a3M93HXUyLyC17yc99uEytQBeDfXr5O33lxOf7Xg6E99PbFQ0t+lw7qkUFe2wIMlCGLJRfEEOQLIuCNIOeb6kMcuJfC7LvFOqRxYHIY0p6b06X7TNYFps/XbM/DV4M87bU8tD8RGhE4xsq6tWjI2EXtqJ9I+Al7DK7A8tL/zO8lxnK4JzC0j7hiarTkXBX/aGm1kETrOr4sEgDkN4arSYIZofwJ2KZ3ny1NTDqb6sWoDf4BkilXA2J0bXSW74MFUfVaNl4LZoZ4yUkcynnfCcx8a3VAs++HQeRpafwS8YuxELDsq9mTwv9rRwTfo=
  template:
    metadata:
      name: ecommerce-keycloak-secret
      namespace: ecommerce-keycloak
