---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ecommerce-keycloak-secret
  namespace: ecommerce-keycloak
spec:
  encryptedData:
    KEYCLOAK_ADMIN_PASSWORD: AgDSMina2ZL0Nj7MOYE4P5JymCqFqVZ3+T/pq/fKdaQ8nFp+NMQhcQVN87xMTslODVG1JkHMV22K4bJc8ZJTHLPsuxUvDsJIKaUlidPma4TEgqNkjdLFq0SpVjMLPYZGDVhW6thJFbexPSk/Lp+zKlNPlEoHzdvCyRhO9Ysga2klJZDPRLCWb4KXHTxr7cATIr/k59EFeuw9NBnKK2aEfdywQW8FsGczT4RnaZixafcp8FvjhZ04mTKGINyFtPVDPu6eeb9InV5+4ZfP9vRlXNscbuQaHI8Uwt0fKKgk0HlN5XrTsfNXfrlAAhtx+hYA/VVU8h0CE+gmwDD02x0q92LbB2t7qHU5DPAEzWQGZnj30CiNiB/J1zN5sT8ORTgx10bjUlQ0A5nKzKZim04KUhOT2/C/dTXC1r0rNRJpgdy2PfO6e9skTY0YQPVCAgqdCCOZqIZKZGf7gO1F1uu5UfPoy2ppP0+u+R7oTeAowoTk/eqRc8mbYP4BpDlZ42ETrpdDpBqrcgfqOnKUGK5NwASd2RHPzQ4rKWNNVWWTS5fV8ZEoOrauFn0l2EiONFBVTLheeyaG/CTlirX8k9GhzX9l3ve2eaTgWZKUHj54mNCv4zgpl3O6W7IFnA6HcbATNfGM7jYd8kvuvpLabejMdRiJcKLV+8GD9Xx6qMOz8PuanbHdejUXofWOPgmnq2zmFPe32Kev82I2v1oGYvI=
    KEYCLOAK_DB_PASSWORD: AgBoQHcNi2NtZsRoA8EQOat94E4nVOmspPY2LTxmFbuiY6R8ea1dh1pmr4aFpab1Z0R163LXXSPWuyoukR/oPRgFGnZ4I024DkhoUvzhS+TLNRTlf15xk/UWYPBoSMPJappG1/zPWJiwz3KXW18vT8tfX/1M5nGfhgSZgXI2UfVPamM9Y3mnCUC7T8mW3Xh53Z7S1Oq8F9SsGdDHf0H7mYoZuJqedVaSt8ouqZK0+d+bBEiQ6ZkmqgtkCrVV3+OJ8gVRoIdKBUqo3BuqBLY6WjZghVLVcxkPozMYlG1jXPtyxaZmm5OfpSdsAGVgdwaw203FZVMmP6ZqZIoEOS1chHj9t7nDr+z/YUzJ37UOxElZgukAWqsn/0z+AvISZWWzA3y8+k3rablpmC6s1xQqX44R6+qAawSabkjN796JJXGSxO92NrPN/O1Ljkar5rJZptm2WKspi901qgvd0XWuZC57TQS26pGwoAqCz6qWnt1fVJVjY9CzrD/+UPMLKqG2UCLumG1UCsHB5DCJJiqSPOYTMkvYRdSoXUvWbi3f6CfWyOlPYJO2QWfAhVU+NIp8iiBiD4DW7lNUcJLZhTAOEqlSB2AmPcoMzpbLUzt419bh0kOYnjl/CQAZ1aQ7DJi5t4QGVsgJ14ryIPd6LPqOwlrU/vHV+2CG56FUxZmc1owDLz9XSm1rr6AiSdn69O2b/nV4+6ZlUC7iK9p5/Cc=
  template:
    metadata:
      name: ecommerce-keycloak-secret
      namespace: ecommerce-keycloak
