---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pp191225-redis-secret
  namespace: pp191225-redis
spec:
  encryptedData:
    REDIS_PASSWORD: AgB+TnKCj+wKvKuiDFtINq2cWCwxtYSmqqnfdggCHjOsWlsjwjr3RVACsI9JjXs9v8WKIMaOsNIrur/PE+0jbZ6qSKUldQzwduMKA2drUQkm2XJ4xmW630UQCy2XLI2/Q/I80HdbkI6Zf3eeQGBpLsgHBEKCCRWtW1srVLr3gs25tqfOtWah2GzdnG2iIuWLkU0nsnVyua4nz7lFvWpue8lb1cziK5eiIPGbWIxQOCbDJcNctNFM7XmvtAIhR5LNcJ6vs1oJpvc4urSpKewo2VgO7uet+ZnPJ4sV6//brOHE/8pxB+TKnhlFtSnVfNRAQE5mrqValigKLUMjB6AIvX8AYDKubNbi7GV3Hu0DNUuPRIgn8Cq+tIlakY/kOC6IM7bmAuRiiAGRx0xswHdWK99gXRpgbIIzyhbi+o58tHmDDVhHBexBt4m9UhCIegd+i83l9am0Iul5fYi7zOpALxhJoWq2qaMTqO3LkRLXPqvcfgi1d5vW8KcocqfpmxESVTNuNWGi191G9vW+iejXENT66YSkPBrSs1uokw06oFUHY4+ueoCZLIvVPabKUumznW8blV1ujOzg/X/V82M8EqppRxZ/soESb8ZAE86T6vPIIvt65I4JCOv6hflFM1HnFPV//NMidJUUerdk7Z2p3ZHBTT3ucZKt3/GpbtH0wXzisV7ZS1qknUvJZPrmwCid3GB/W5A80ZJMm0gVZWY=
  template:
    metadata:
      name: pp191225-redis-secret
      namespace: pp191225-redis
