---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ecommerce-cart-service-secret
  namespace: ecommerce-cart-service
spec:
  encryptedData:
    DB_PASSWORD: AgC/YUengpFcccMheAT8+J8IunaNJxdxTcMJ2AgqZEW1YZ9xn3BAcXlz47tBIYzws6pZNcC6lAFww2xg/oZL/lXNxPpYnDn9ttMToDqNKiNodMQMJh9vqS1yqrXCkHh9HD+HmW2/s9OZfudxr9FcAIHWVaClUjIvwu7UdKgoL69Gd7V3oK1lI8D+bcOOvHR/QR4EBqYxyiLXdrbRIJhGXOM0ADrEd7ihnPW03xKINvAx7YOBzmktbPY91d7GaM75qLbo0+v6RJfLHgep+FgD7+PV4t/5LhWyu5r8xOTq2qoII8llg/hU9xdK6DMDAsPofQpEEZ2swCnluUMTWbT+jMfVXwMRf3KdgIe2DvI3I7qXsjwlMit6akH5ykE6DjDwpcveJlJfs7cyt7xpCRqpkcJLj/aFVFC0PP2IpMp2wnYOMzB5Ux6IrdsYm4NiC6QKooxf0RVpHSNblfC028DbxqKw59e1nPYUlx7ecZi+56rOdrPIib/CWLoF7zLmw9t0cnjDm99gLyiNXGnEOTIDtnDsSlXz09tJefuI1+lwlJ71lmkbdAPL6Xh05zWqoYH5QZpKc9e3tJ1Mf+foKis+Fn/TD/5WuxVFhcYHpETPuUN5A9onTpCrIHsnuNnCyizLJ6EHQnRLrBzKpoc+9r3aJ1OxYUdjEvjK6rARIUdD0Q5wqDmSq6uYdHmX6X1dRhCpflnc5Gr9jKk4zpofgEBxmDo/
    KAFKA_SASL_PASSWORD: AgDtkgswXsAEQxKDmQ4SQySqhEaYA6kG7p0f4Bcbok0buxGrA4WjlCClrzzs1Qa3YCWfVtbab13f49DcaKP15WA2XRGisFrSm0vbqKqlFrF+R938WFONccLF0xgGaGd7RXSfXkWSqUz1H6VDoae1n598EaxJYK6Q4otU+IqkjtsWcebixz2R8SjW69ySXxRJS9Ilm+67yvGWy3CkSNUUOqXp7lXmGN7ZJfexgPNfKhX0493cCt651OuSClvXJZ35g4n7ybIeNNU40ItGLDGQh+BWI3NzEzCdCaMcJEci85Asm+cmw+ATQrC28X4z9StY+nLCWje70hc9D98OXB8jDRXlpSHSgskgnzCk6djFD4m6eqXDMqiyH5HDEHd2LekYEpi0NS8BBLJBalPIt3tg03qp0bq3grMUyyfL3f/a+yvTycnGZLKMUiL0ayi76mobEinJytpPFCsj64pMXWiHCA/JryJ1neYUnwvtgePvz7fK2JdU0gBjQJu6Od9qaw1W4kjVblUV012DtoC5gCxqOlS9vF8w9Ygv+w6j8VotYVoE0r6tzcz+Ny0vGwxQWPM1k+U8pwMbe19cMmukw1CZRBj9Vh0JAFkWGYxnEqiq/NyZp5+NLAfV3IX8dWJm2Zb/5o4H9tMITcpeV0GLm6d93SsVf14FNd17bP720wR/IkvHJt0vbVWjusEdc7Q9BildSIcTffhh2/fx3P+hUsNpRDviQYDvYSGtN6U=
  template:
    metadata:
      name: ecommerce-cart-service-secret
      namespace: ecommerce-cart-service
