---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ecommerce-cart-service-secret
  namespace: ecommerce-cart-service
spec:
  encryptedData:
    DB_PASSWORD: AgBjAMsAAzmkyVR6tPYdBETiOWIj3fZ9UKwGy1nUhOlsszNQrS5VdtA2gcybqpXWAZS1gJYpcFxKqJfx1T5WLnBM9NnrhM5dVQ/e39PeE0ttUCLvBXYAjPgOTu0GAkcKIH2rFWyPuZguFPouVHUx/RnSclD/V8XajGp3HtcLHtK5i7HHEkHYTqEWk6Gkh3ySXBux08NCQ1WzOwb0lBaQNSU823tVmvwgQ7DxwNUvdKg4NgPm7nMLgmfqej2OJ7fjxwl4ezmSpfZBu7RpCptkvZMDKV6MyZj7RtKqCrWgRUHHtbAKVKGFRQuGpQNxz3oJ4IVInZTst/t1RmXQU5vUqULCf0L4rpV2ecHyBQpEYULfsPP4m0c1CX/PPEVVbx8k2mow+n/lPCD2v30vSG6huYPFm5pbvsB8GwxgVkKdri0RI3ml/Z8AjNXGpFOcqBKYVjpX91dDmKODAxQgP8J2NqbsWvZfK0AcZTEMcQkcGhygxsYu0Ye2eLh8SKu6sqS/dXig2a6bwnVAEMemErwmmUenaM6qymZsWOfhKXWBKavNkzaFx9nvpqtxc5g2h8//LZrImmu5TBCHKK3MyjJMJcbcrXM/Fw//wvpiC7h8FY0dwP7j3313thMM1OxZ355AJMFWa5pJJzMyTnHyS9Zgy+TjMdImh/8QmTXS7AuvQXNzRNag7XIXZfwhkbte7iYUNLo0S4tdmn5rADfJQQ8Gx5B9
    KAFKA_SASL_PASSWORD: AgA4AHrxizodedkDvaWMgsjNVfYNQUeuvsylaycYDHrnHsz5nWoYlLAdZXKSBvijrzAPHSVFOVMHpgEe/MsBdNCnTbk8DBXTXJOC8Q3JvyIKURGOUJtpx3R/dx30oLNG+tRXmxFdfFs1hoCBNo0M0VLTb3suqUJbgPbNdE8DEdKs5aUbzgwoewcUAtNjFp9mucLZNu9KrFU7zJhjvUjJ4T7UsknsinsBoArm9w2afIaUPI6k1T981FMGSFGqV2LncaKFUiyZVij6X+JnANi8Zo2qsXKHw1jTByfSXjjfj8dSz3C2WUjzfhYJdOa4bg3wO/LJH0yziUgL1G40ENLPWEVwUQyypKhFqwR9Co4e+3a6NWJLzm7dBJH/jfCOcz8ZQ8M5xU1Mpl27TtezQhsH6QaDd7shlWrrPplaPF7cyLLvzJvpJlaGcbdHoQAqqe/dDF2aLJlyxFhVivzynkMG84kbfno5rVf/zBxbtJ0X25gsCzsegz8KiIltVHj1nSgt5p/wv1++G6AT9blEsPUReONya1SBwT+wxWQPkeFJEIfSCA/Ul1WsXSTWyXWQIlOdDthieQQAcY9aATId2CJq559cJak4bNjkqNfVCC+I7766maWuSFCfC9r3OLY+WdM5f4mTOX/1okGmuCDrFk/c/oHCC4FiUZfbLkn+ITM+Ep3HLIKWsckgvdAyhxY9EHp8coevIwy86BJ5e9zh8LJqiRxsehNOakEjft0=
  template:
    metadata:
      name: ecommerce-cart-service-secret
      namespace: ecommerce-cart-service
