---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ecommerce-cart-service-secret
  namespace: ecommerce-cart-service
spec:
  encryptedData:
    DB_PASSWORD: AgAFfTIZvBnOBzysuHoS7l4VptRGiK9/CJyxM+lU1rI7JY6deMvVUP3h//BxQX2B9F7bRG/WW79vGk7eAWhGCzREqu+wc4tSq+LLXPFuT2geryzImF/Uv1NJ0t7DlJZJpraA+oN21XA5CXtYq5wVTbvclthocBiWzD/qRso/1EzE7gdGYCfp6Q9HJQxBcl/s5o86SaWoOC35+F6wYt3FCQ+RY+kI9DSifGAHtZ5yDo1pVcTj8LbYKq0qkRermJS0XZ9oyVrBqe6RQAfz7eSO0qSFSZdxf6j8CNplY6QnUO/dDc5NPwgHXwJBa7L0TkrV4jcLGAV4s6ioBe3exKOySEFBgwZPq0U9DYrqcpFGHiePDNOYY+2inDOMNNCS4qdvkXZDVKPgLTZO4oTxMGXjPMVFYS0h5SBqvcr/tX8jPRNv6QQ74NnCgt4iURUdGMcCRZYC3oou8+RPU+ITEmtgJL+ekkuD0//seS5KOGyA86Y/BiBUPSA4HbDslWVdLWQWhZL7j0A+7ICyRhxKYT9Ua9slikdvd70vCDL8ZhHsGIir8XGwsslJA143Tjb/LcN9qolR680+FdFq9+2I9n0jaUTt2GyPXTCIA0hx1ZGIkM5+GPNC6pbPDJGQXPxFrdWTiebd+gDZ72dQ5zzgJ1XQ9chUn+1yrrREpLXJquK//pUPgU1drSRp0DhqzKli1WcCUCOppNkS7/N0Mf52QXA/oawf
    KAFKA_SASL_PASSWORD: AgB8QPUmRcEK+LeXaKsop3XmL5xzro/aonrCetr3ACMstxda5I/4/PzqP/KsqJEQBlLr96TmCU8zVJGlPmOIhYKecrg5jNr5yYLvvIAUoJ4RMjUWg7iPV4Kq+M/sz8c7WVXH0P4s+9vW4YZFGEWM5Z5A0SPmpfgLUxpRBKh2kIW+UWbQEKET7LwSs5wXOWTO9SzF8BwTkN3+aHNLdAalXhvyIjLzXrb5RsGgCPbcuWXFcqxUIe1AhLpKuNdvDYmA7PgsnnqWoNFDvdtdgf3MzvFqy9Dqvd51ogTuSQxp7Rs4Pqqvwgxv+6KnKKw3klyXZ2zQDY/8Gjb+/fi82WWljnb8udXOtmjz7SvC1L/mGrf/qPwgdHVq2JKHv84fqCb4xo6QAR8pK8D66bLTG/xPRpaB/uq4yB26TjzQpZtfTVpkYasEheYdnvt652ADBV63gqjAs2qhAgcH4m42rtY3tlHTqyN4lRDqLMW2mnqFZXw/yCNQogRuuVL93gA4OWgo4GR4ft/KavtGkVsQgc+FizdZWJtd3xqjk7xyLiJWnkRaIPElLE4f4L3PI91UHBJwGnknybgEQuS7EYRzyxgtbziFK5Za4z6dT8LtvAlpv1wFYpE6YGOyhqlxCtSn2RLHBMzYdN5aKLDQVqx6ByhCyW042koFXk+oJIAIKoJwd9QgAmpRo5PiqikERI6Kus+BtHRrle9n9YO+OpJtsL3kLrZJm+ZZwMO1D3s=
  template:
    metadata:
      name: ecommerce-cart-service-secret
      namespace: ecommerce-cart-service
