apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: tenants
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/thang2k6adu/kubernetes-infra.git
        revision: main
        directories:
          - path: cluster-dev/tenants/*
        values:
          image_repository: |
            {{- $filePath := printf "cluster-dev/tenants/%s/values.yaml" .path.basename -}}
            {{- $content := readFile $filePath -}}
            {{- if $content -}}
              {{- $values := $content | fromYaml -}}
              {{- $values.image.repository -}}
            {{- end -}}
  template:
    metadata:
      name: "{{path.basename}}"
      annotations:
        argocd-image-updater.argoproj.io/image-list: backend={{values.image_repository}}
        argocd-image-updater.argoproj.io/backend.update-strategy: latest
        argocd-image-updater.argoproj.io/backend.tag-filter: "^[a-f0-9]{40}$"
        argocd-image-updater.argoproj.io/write-back-method: git:secret:argocd/argocd-repo-creds
    spec:
      project: tenant
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        retry:
          limit: 15
          backoff:
            duration: 15s
            factor: 2
            maxDuration: 5m
      source:
        repoURL: https://github.com/thang2k6adu/kubernetes-infra.git
        targetRevision: main
        path: "{{path}}"
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{path.basename}}"
