---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ecommerce-order-service-secret
  namespace: ecommerce-order-service
spec:
  encryptedData:
    DB_PASSWORD: AgA1ccDtclLmNXZJiYk5rBLHm9YcfA0rhVX4+2lJxP4zuSyOui5ntgy7WerJzgjZWSSVZyT1X4G0L2K4NKJdeO474skzhfQQsKe9BW1NmQK+vHUL3qhLIXlB8bXP9U2wFxKR+D/3zC/T2QfYkEBkYtwwSn+LBkfYE/xYYSmK3UXn77omlmuwkYOhcFsrA7X+P1h1moVCOajS3IQTXekHEBEfmPVCZHm2bJaSx/oKyyiwQ+O28LrB5/IE6YJdk7NnofRbxIS4kH6QS5Jr5kyxyE4QIJ/Qktv6LdxY6Rxrk+7dbDBKat5O0u9GLukqvuzK1KpeymTYJxuLPgcWCJ89rbL0eAv/w4zPAXILcXOuYX/2bY2Gs7M3pPnesg21p14aaKLnJ0D+dOPxpCUTqFwPRnbpirVgI2JJFMWcnWOMKpmOQYEN9Z/iXNUHS1XESOHNgDS3l11FMiQP6la5XqLldU5yWoLy9ldQXnbkrvDm/LMyC4f9aL/zKMQ15oKjhK5e1DylOrL0wGQEyUQuSwTttPsEZkmjgAg2Yx70ispG6zNcDenIaqYnWCSGWFQdE1gXi8BwzVEvCYH61/jJzc3RLrMq4+hEzzPOvQAe2wT/NvoulChWyYrGY5PQrSKdyznL+A2vWgvDKoQjfLkeZVz+lcgHtE4UXMko0EvJwuGa1CkQKbS3u17YKHqSEacuzGk+d7V1rEf2bS/9AcrM6+G59EJ8
    KAFKA_SASL_PASSWORD: AgAFPoM19Zt683pVr+mfQ05YxRZSO0facxA1o96f+VgnBTfWGm+FpsUY3ICbNUpnZ+QKZDzTrHi4KZsJZ1l36cLK5ltgnPgHD+jV3bayx2OL2TBq9UYYuI46wtM1sDiOguVWAgkKwn+gOUSTk6gCeue4EL/fAdgfvDXs35LKsAW2vP7CZbjgdi4sHRHnvLQcVrigrVW19FV12rwp+9n0B4KDnadtY/reu3xt9ENCVKw0YfkFGDFWHvD4eZ657rO7W6EZv+7SdkORGUnRvKk1G7QdGAhhk3mfpgNAL1m3qLMUjI+BEdJWqgvb9YsFQPS6C9R78OFXN7Me/rRecrIc+gg0GCflcUPCGm2R+MKvmSx24CYNj0wH8D/tMM90re1+WfjhkCLiN32uxHjyjbCNVrRRqTdlRk6TQCDYG5orORR3g2HI7+Xn5Jd9BC4WArX8z/EtA6DzOmBldOWcF4kSFR7oKjfqwZuhqSazo+9/JPH5+dgklkzR5pouHCx9+jpcWdb47zSwmZ7zZWDolWhZsYDJMD/7QZqRVkhDfc41DsrrjmvJcy57oeaTLoM397jLH5nxpVfhVqbFz98gLcO24MGwHVCbMZlTRwt/5LwlDADk29SQSjB0tgJpBY7BDYw9Z+0H5KxMJtD443vdheQO+lH2IgpynnYmfdtNvUhNobuSHZoVzW67BSn2kCBCzR5zHt4AGiUMiD0ia0EwC1dCPLc3RAvW9YIswNY=
  template:
    metadata:
      name: ecommerce-order-service-secret
      namespace: ecommerce-order-service
