---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ecommerce-order-service-secret
  namespace: ecommerce-order-service
spec:
  encryptedData:
    DB_PASSWORD: AgB9zIVkalSM8S8C9jeYzrl1oM8fW83zoe3hTXPtL766cOoNg0ZwyFjd9yZVp2cV4yB8wXI0APG/hMQAPHAWcaCAbOFMwyx2ShoXfYvADB1D8VUCsZU+nGfyW9/i98pPy6a5sAgoeIwcAG15jJdIAn33D9t3QAmAYdFgcYHjUNiJnzDDK5RHoEfjTevVHc7RSPbc+8Ygu1R5w608panMj/tneRR62f6kVAaJeELU92Kho9mvAEBLvY0j/y+M6bB/ATsZEUd2QEKWEuf6XBWFEnd6AH/AItqUqf7jBztKK0Mm7s7seEYoCGpF0tWiZnthpMTgZMOzB0dK189t+Gw31f3Rpfm7dKaWMGr6GY2HGpSjWd9leOnK/HOKGRk+ZoD9gMXDaM8HEXJGyYOT0b60Dc9R7DirsVh64wq+KoRgkkNCn87ECHmwECPVF5wJkpX88SjHdndl8x6w7zTir+aYlATiqUr+aGCa8FGD4UWVv++UlT/at/V0Y+S48DF6bqdBoiyKEQOTU8TKWQe9LMh5xNXzUNotML3Vs0mH41pMvrb4ht6+Abn1rErGwi0tB3Q1oIp+H6PDbBh5v2BYDM60pEh21SGDihNuMyNw+XrIHpXt7WAQx0w5QVSchpy4+R8puj9w84ultXreTtRuauPkSKs7i9TzUKsD+Aep3HeEe4RwMJe6IKV9VcrvsSiZmyBg0/+D1pa6ScsKKMRXLdec+ouH
    KAFKA_SASL_PASSWORD: AgA6VXi+Dxb10hfyYUhP7ffmzv1Ff870oHzjdp2IpWHCzCneLbKUpmhtGdLN41+gT4rGeKayC2FDOtyFXMs4TfhT/c5rJ0c/hd7JjfUVAhrppH9bJrtrpTecGqtkKF3rlHLnAXnmwNZ0zZS7ca+MfUt02ESh1m009aKOd5KofcKcL66VS3cJ81Ls++ekJRvPd0fIP7TXaIAgVApc0jyiJ8AtWdrwTaixHfZ9Jqe4SaFazEdVJeXZkfCrMaDwq9raUpW6HjHVbsKXYIjcbnZJ8Xg1QWeGDuUTKtDgRg8IyS3Anejy6F43siEZrxP8x+at/Szwj5hdYNs/U4xcU/BJWijujnkakYt9opt/GewfOqa8et0KKYI8Cmwxr4K8surzH8o4cP30JppcKN6U4khwyPJDregEryggvscTbK7P1xQJOIMHbpUp9JK1E8lanPzscf+pRzlp71Ytul8w+iMTg/g3aXUEiSW+EEgWxTdmXuuPElzg9VzsJc+5C6RjnqEieYJFbPrSuXCkDDP7gH1bMARz1YhedzmDWWJ3kY+GEZ4Em8ZxgBjEwsAED9kzCoyX+VpfjQIMHz10ufx6cod+ZENGJ7a0abctpjOpEb4Z24Oa16GfetsFeMd9q6JHLujVKeKs6Z02+AKM4W+qfSQqQO+yoh6fwKfkrNARDGTRlLcx3FTu/qN/+maBI/1Eb98Tn1CL7v1lrGoimkyz44OrQYyWC56vP+xwAZU=
  template:
    metadata:
      name: ecommerce-order-service-secret
      namespace: ecommerce-order-service
