---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ecommerce-order-service-secret
  namespace: ecommerce-order-service
spec:
  encryptedData:
    DB_PASSWORD: AgAwgLeZFm+uVKviraUr36w0LPA6FGtlD7CLZiyeXleTeNEIxvQBOV0Bkdd1eBL2pPnvC+ycRlHmuenm174ugoUTTmoP99wcltzfQuVnaDj8vPMlUvSCiltD+yCXxmGrI97c7QCjVge0cfL8ahMNuJBRsdZjFuM0WFyWYlUc1HmvXlHGYrb8f/u+4/ZCZecC2KyEW1Udzv/tbUavt4GuOmDF06aj9NXMpXGEs1zxrxSKbNHlvj3ZBYx2W1HsXDB6LlZOFCdRD6A+ZIBQGvN8dhEFNkWh36fp5XUvQGEigh3JbruFGWJCvmIhdVpWXNR6NWtH0Vq6WTmPre98c27oYimVlw4tZdNcIeASNrkB319+3nw3FDkYO6mNj1rMyqzSX/bon5kFEqDCSpzVvSJYCjQIx/NMH3j3ZNDq6waohNz5b1173n4NEBa51KVbx8uBREG2aIX1T/271T67NpBqZ8XzK7gm7cVuUltNRaGN6zcKm1TP1eQrrmj1aTmZQjr3J68HZOId8aDuTQtzSKcBy7MfKcJ7IFLC8g59Cd+9s20nAPpHP3A3WNtO2KvsbT4IvYovj78DOxcCA5MQ3II1IjEUFL3aPYQdZqVJIrttGYpLp4dcJdix8thyJN8SofMTItItLqXQXyDbMZH5Qnwex/ZRNehAGe83wGWp4Cfm+fx6jvLZF7/AWGnytB/hJin3s2QMBmnpHN/OkQVVXFDMKtDN
    KAFKA_SASL_PASSWORD: AgB7D6osz3039BhvGrXFxHeqqVg4BuvYbSqm1MWAVkKSJM6gZq4NWk5a/d5o2ZRq8sKb07RUHb32l/6yqANTJ7TURN1tm+AaoRzDRoHEGATrGbwh5yS6Bc9Kxkuk0OUzGMNKSt+LZF65BqQlccfycoNXZhDRzPxyU1xjh5jyfPrWD7AtJrfVAWnWhbk1ZEMwaneFyAxswkS0IVYswhCVMBfxdasnfpZXnPswjVVlIOMvxeHU9FxUkvuoCNZD7GIa3qU0Q3QwnprAFXficXIgJInaoUFNIJc5XOQlNLj8xQMFjDFZSfcVXvgkEHFMOkBFWX5OAE+3PY/FOXscvVisTNIZvRINvqzoW7lmcWmHY67gH1wkORidIeeFDFhC6JNfNtQXKXUybLtaluav0zyKwu3nrhZGP25qY26JhMj8JJh6SkmS8lirj4p2YpedJHl5Y+CVNGIFGOj971Uvfu/b2Lb5JsuGlF9mIK/+ZeQWFljNeVJytRWi3sdDCQQdZVCik8s0HqAr7jVGqMoWiFak+kMeVI/cEMyq1q1HVlEKmVTOnMr2vG2MAoFU3UnSZXwttGpxyGbsgm64dVL2nrSi4Uhjt77NVXCq3xI2t8mdw+RtDG5ilOMETzNUDHnVrGPvtX1Qq68bcKOmVnSV9W+SqBaAQpvu15zy23OH9tVhX5WYr+INP8TE8zrpf3cSGM5Zx3drWikm9ZIeeKGSi+nPoxAhwTOHQOVfitQ=
  template:
    metadata:
      name: ecommerce-order-service-secret
      namespace: ecommerce-order-service
