apiVersion: apps/v1
kind: Deployment
metadata:
  name: prod-livekit-server   # hoặc dev-livekit-server
spec:
  template:
    spec:
      volumes:
      - name: keys-volume
        secret:
          secretName: livekit-server-secret
          defaultMode: 0600   # hoặc 0640 nếu muốn group read