---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: livekit-server-secret
  namespace: livekit-server
spec:
  encryptedData:
    REDIS_PASSWORD: AgAashxpXFFFfDkTO/PwtDVmNOae8dO680p5wYy40na5XBBeio6L7sx2aKKBou5T0hwExqg+Ut5fsIGvDgKe32xqUMfTHokCheet633C4ofjS66p+85RbUcTXcZGb2coj+A3ZJeO183khRiELUPSuNY2VPWRwHrCATJnC90Y9mIMzR+ctceKEqLw1T+B1XsXI8NWGgoIDthzlE0ymfLtDYsaIJjkR4Vliqq/2p+OGL8nNYBVp1IJL7BFyhctyOcEBrUWyhG7hh7i7iduwAVfmVYVOzE8srW5teMotdWzVsVu6BAMW2yCKYc5JuFViMAup1ZwngyEnl8BYSvaM2LqM96EvJeJSLYeXg+37eQt6KCRyJ0o3/TJtvlU1DNeaTHmda/YrllvO5vjZgTcmHYnND2ZzxdvkTQiGZSnfH265Na+/VeyWNP3JinWquG/S9G9SI62SvofNGn1qZeiU731uPGcmESMxDmEO/2ZkitWS/tjuPVcuaxHIILRB4TTZuJocTx/AqvTHZtOEQApBB2YT2McgqycfK1KOOx5xnK7sGY0adkwDxZHqy/USlId1QmEqUlYi5iUQbfSpt+zbK7z8P7CsXvzzZxMSVZRMFgOoFNFrrg44slWVdDnsNDEqAaKxYmOl9WRImvn3iJx7mD8CswYkYt7byU9XpvLWkgVE1boax+/+gmVy5c18DfG2ipdaqtNTtBFF4GrCpYAt2jL2zWAiXwT
    keys.yaml: AgA2+fNt/p7NWpwhOILLEyqvw7JgVOwrJTwbNbbGL5CyC2OQ0RwdSGwy8xdddi/8lVax/XmlO6UnHGYuNhZnsIYlcuUKfyv87Mpmxq4FxWNYUZtSeS9lk/1gNgUJbLPDzamVaeo5AvSzofI4uNI9hEWqn4tyqSmXy/sBKMAPw3kALpUCCIqHdmKGy8QMVGRYCNe2glIuYBGQhTMl64tgKjtGGaXCAXM1gP5peJxr9aj+wBigRotVjgauQWebNDKSukT26TSevVuIFLQHJ69bDrMuBS5Yqtc18VREkk/t48krJ8OQ2o0wBysqb26r6znbohWbyQ1VwZVr7wXYGyejgUVlqsGS3lrJRAQQHqx6itsJaEMQd7UWxzewpErXNfQZCTLndiaoRLerCHUQTiGlBE5aVF8sH6cyWkWIT6B2kUQTRLamJYZYSLltR8swt2EerLwrCL6zBulLm3NyN65z/qS4LCHHZ68mixm+fqNpJkyVqCOLUILqlIEG57+ug5Pbp+l4Uy4auMxvyVuyAzuzn1s+LMAEi6O8lwGQTvUEW4+UF7ks9QRDRnBc+lGZCTSoFU0avVeGmtdHs2s3DwKIR/VQ+thuIVPdHBHqoCxnjz9TkHsYhpaWm3xE+FS6djIHtnR9+2wxLrvlXl/fKX3YeelAkSw3LEpNSm9MI6ZcvRavdpvnLTb89M2z+D+Xl5Tjrq/xxaWcvsrTFQZ5sTDpun0uYHlsGI8PFd3qD6uJFUn2pCfekKjhT3fnxnX9Tm5poj9AwA==
  template:
    metadata:
      name: livekit-server-secret
      namespace: livekit-server
