---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: livekit-server-secret
  namespace: livekit-server
spec:
  encryptedData:
    REDIS_PASSWORD: AgAQSR4QzFgumafn9qubX6+Ssa5Upllc3h4Tq26j1MFurSEwn9fiOoPI6SuL+Mcw814NrdmVHuYn4ar7qvggzqOhdmDztLI8FtKXjBrvDdF1NGw5AZXb028K86aNGYM/DZ8Suhdq9zWBgr+1V63LOki4xqfRiEREXD0O0lRpy8AWC0NU0A8yavUJ08dZP0RUPWk9YYl+5syCIwHqavRs8TfPAIBEHNtWTJG2AJ3Awd8ZA2oQeLfFAaxfxAMwiN3zmV1fAV8MdNBGdGz1tCLRsXKB3kpF3ajJ6d5Pq2jLtRIUVTtdicQzasJt1+8sj2zsExuslbGrruoItel0hJ2r4WdP2QegDqvN6TFYOVS5s963MBWcipKJIREAkiVhT9lCn5yvWcs1hG+BpoWSoK6rz0V3T9MKcwEXvMHQdSJ7atrAGErbdzR5owfgFFo8/ebwnEqv74xXWCBwuplKSCJ1uJfafHqpAFnCx59cYA/yWbRmsobeMwYatdDCxlHC3g/Fz6B/O2+4NoBWtUTuumY1Yewo3Jt6oH3LYMpvcVZCvhY4cS/P0iGDgqpoRZ1xQYkqRO/97pyQWO3w/qH9SPTCox9dUC7ZRpFzD4RE4LRkGfHS+Db1ZhsvzFTAqQRmLBlAZi1zZxhiOb2kVLiX5+9iC+4PnnQVQ+X22HadOnc7B4QOt7hw9HSl0fx7h00tVy4+VCrVPGB0M4+MCHp9EebLTw4dROzL
    keys.yaml: AgDW/8qlJDv8vEfyMymqKqdbQSjX7q1pGWaEkZIexsTkarS14d8STVzbh/h0+3o/By1MvcV3QQlk4VeWNZe0wz24mKUY/GflUEZ5BtSWGnzzvpPBme+r3TDw1+dSSx1tyOhK8xDiPTh/xoSKYUUvf/WUkpfx7td/Yy4qJy3vrkbEC6pye4CR81uqPSjjbWxGnV4xSUiYVQ54R5sVcA1D71MHtUhFGR0+JKFGLmeoMsTqagML88tNpISMlKOv8s/Uz31JtrryXhioJdv5Rgtt2vapQnN7WTqSDRd5i6hGZAGPK4FoTDLIF9012X8rctulE5EofKRBIrCzBheGYhpBLImeHJbwf+26o9LdL5qGx0imH5OnzYMLdIMTlNSZlbsohtltTgtlQQVIiP8+vxxxkt+u71O+s0HF8GbY8pCQuolmbtd4e23pcphCIQS5ls4WsTj0Kv8Oql8ga2l6qVojYx1NNbShlk/0ouCx211GrwxZO8uI7sxGpIZC3SFtXv/6nm2f1T5D1SvX0Kq6gzEekV1JEvcZdNzCtNHgbYmn4DJ5eGggq2NP7GmUUet6FXX7hhHZ7Yf0LA1BcoLgwQdKzjislQu2ni/NroWv5Ry3ZR/0dTsSkiKJ+VS0p+u1kheScR5jwwSdZ/Rhe6MszwGHI/THGVgPjiFE3iD8C0yIa1ALxE3XRKy3dOZNfa4ogek7hyTBaV6Ls/HghW4LkaTljC6A+9vrNDH2k6AcmiCKmhRyja4OxnkGhoG287ykKGgDLDuaxVehYQ==
  template:
    metadata:
      name: livekit-server-secret
      namespace: livekit-server
